//This is a list of channels who are shown with the !live command and
//are shown on the /live page.
//Channels that have leg_bot in them also have that behaviour without being on this list.
module.exports = [
	'seabats',
	'voxlunch',
	'james_lrr',
	'thepettersaga',
	'loadingreadyrun',
	'streambros',
	'darkmorford',
	'nullrush',
	'ekimekim3000',
	'raymonong',
	'lambmower',
	'sohnata',
	'nfstreams',
	'roastedgravy',
	'magistermystax',
	'mistahfixit',
	'j_s_bach',
	'lordwolfwood',
	'doctormia',
	'kinogami',
	'devinsanity',
	'charlofsweden',
	'cattleprodlynn',
	'roosevelt',
	'desertbus',
	'hiramas',
	'featherweight_',
	'rayfk',
	'themoatman',
	'metricos',
	'senstaku',
	'thefilthycasualplays',
	'uknit',
	'navarran',
	'upickvg',
	'malfunct',
	'catcard',
	'elcalen',
];
